includes:
  - base.yaml
model:
  model_name: BGRL
  dropout_rate: 0.0
  use_bn: True
  last_activation: True
ood:
  ood_alg: BGRL
  ood_param: -1.
train:
  max_epoch: 100
  lr: 1e-3
  mile_stones: [150]
  warmup_steps: 10
  mm: 0.99 # momentum update

