includes:
  - base.yaml
model:
  model_name: SWAV
  tau: 0.5
ood:
  ood_alg: SWAV
  ood_param: -1.
train:
  max_epoch: 200
  lr: 1e-2
  mile_stones: [150]
  linear_head_epochs: 100
  linear_head_lr: 1e-3

