includes:
  - base.yaml
model:
  model_name: DGI
  tau: 0.2
ood:
  ood_alg: DGI
  ood_param: -1.
train:
  max_epoch: 200
  lr: 1e-3
  mile_stones: [150]

  linear_head_epochs: 100
  linear_head_lr: 1e-1

