includes:
  - base.yaml
model:
  model_name: MOCO
  queue_size: 10000
  tau: 0.2
ood:
  ood_alg: MOCO
  ood_param: -1.
train:
  max_epoch: 100 # 1000
  lr: 1e-2
  mile_stones: [150]
  # warmup_steps: 50 # 100
  mm: 0.99 # momentum update, 0.99

