includes:
  - base.yaml
model:
  model_name: GAE
  use_bn: True
  last_activation: True
  dropout_rate: 0
ood:
  ood_alg: GAE
  ood_param: -1.
train:
  max_epoch: 100
  lr: 1e-5
  mile_stones: [150]

