includes:
  - base.yaml
model:
  model_name: COSTA
  tau: 0.2
ood:
  ood_alg: COSTA
  ood_param: -1.
train:
  max_epoch: 200
  lr: 1e-2
  mile_stones: [150]
  linear_head_epochs: 500
  linear_head_lr: 1e-3

