includes:
  - base.yaml
model:
  model_name: ERM
ood:
  ood_alg: ERM
  ood_param: -1.
train:
  max_epoch: 100
  lr: 1e-3
  mile_stones: [150]

  linear_head_epochs: 100
  linear_head_lr: 1e-3
  eval_step: 1

