includes:
  - base.yaml
model:
  model_name: DGI
  tau: 0.2
  use_bn: False
  last_activation: True
  dropout_rate: 0.0
ood:
  ood_alg: DGI
  ood_param: -1.
train:
  max_epoch: 500
  lr: 1e-2
  mile_stones: [150]

  linear_head_epochs: 2000
  linear_head_lr: 1e-3
  eval_step: 2000

