includes:
  - base.yaml
model:
  model_name: ERM
  # use_bn: False
  # last_activation: False
ood:
  ood_alg: ERM
  ood_param: -1.
train:
  max_epoch: 200
  lr: 3e-3 # 3e-3
  mile_stones: [200]
  eval_step: 10

