includes:
  - base.yaml
model:
  model_name: GraphMAE
  use_bn: False
  last_activation: True
  dropout_rate: 0.0
ood:
  ood_alg: GraphMAE
  ood_param: -1.
train:
  max_epoch: 1000
  lr: 1e-3 # 1e-4
  mile_stones: [150]

  linear_head_epochs: 2000
  linear_head_lr: 1e-3
  eval_step: 2000

# lr=1e-4: id-id: 0.8857, id-ood: 0.7714, ood-ood: 0.7714
# lr=1e-3: id-id: 0.8857, id-ood: 0.7429, ood-ood: 0.7429
# lr=1e-2: id-id: 0.8500, id-ood: 0.6929, ood-ood: 0.6929

# mask_rate: 0.75, edge:0.25: | id-id: 0.8786, id-ood: 0.7571, ood-ood: 0.7571
# 0.5, 0.25 id-id: 0.8786, id-ood: 0.7786, ood-ood: 0.7786| 0.5, 0: id-id: 0.8857, id-ood: 0.7571, ood-ood: 0.7571
# 0.25, 0.25: 0.8929, id-ood: 0.7643, ood-ood: 0.7643