includes:
  - base.yaml
model:
  model_name: MARIO
  tau: 0.2
  dim_hidden: 300
  dim_ffn: 300
  model_layer: 3
  num_clusters: 100
  prototypes_lr: 1e-7
  prototypes_iters: 10
  cmi_coefficient: 0.1
  dropout_rate: 0.0
  use_bn: False
  last_activation: True
  # w/o BN, last relu used
ood:
  ood_alg: MARIO
  ood_param: -1.
train:
  max_epoch: 500
  lr: 1e-2
  mile_stones: [150]
  linear_head_epochs: 2000
  linear_head_lr: 1e-3
  eval_step: 2000

