includes:
  - base.yaml
model:
  model_name: GRACE
  tau: 0.2
ood:
  ood_alg: GRACE
  ood_param: -1.
train:
  max_epoch: 200
  lr: 1e-2
  mile_stones: [150]
  linear_head_epochs: 500
  linear_head_lr: 1e-3

