includes:
  - base.yaml
model:
  model_name: GAE
  dropout_rate: 0.0
  use_bn: True
  last_activation: True
ood:
  ood_alg: GAE
  ood_param: -1.
train:
  max_epoch: 100
  lr: 1e-4
  mile_stones: [150]